/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asigaula;

import io.javalin.Javalin;
import io.javalin.http.Context;
import io.javalin.http.Handler;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7000);
        //app.config.addStaticFiles("/public");

        app.before(ctx -> {
            String username = ctx.formParam("username");
            String password = ctx.formParam("password");

            if (!isAdminUser(username, password)) {
                ctx.redirect("/login");
            }
        });

        // Configuración de rutas
        app.get("/", ctx -> ctx.result("¡Bienvenido a la aplicación!"));
        app.get("/login", new Handler() {
            @Override
            public void handle(Context ctx) throws Exception {
                showLoginForm(ctx);
            }
        });
        app.post("/login", new Handler() {
            @Override
            public void handle(Context ctx) throws Exception {
                processLogin(ctx);
            }
        });
    }

    private static boolean isAdminUser(String username, String password) {
        return username.equals("admin") && password.equals("1234");
    }

    private static void showLoginForm(Context ctx) {
        ctx.render("/login.html");
    }

    private static void processLogin(Context ctx) {
        String username = ctx.formParam("username");
        String password = ctx.formParam("password");

        // Lógica de autenticación
        if (isAdminUser(username, password)) {
            ctx.render("/success.html");
        } else {
            ctx.render("/login.html");
        }
    }
}
